### ISSUE TITLE
import sys

### ISSUE THREAD

**Issue by micopes** [micopes/Algorithm#1]
1. 재귀함수를 이용할 경우 최대 재귀 깊이를 설정해줄 수 있다. 
```
import sys
sys.set.recursionlimit(10**8)
```
2. PyPy3이 Python3에 비해 일반적으로 속도가 빠르지만, 재귀 깊이 설정은 불가능하다

**Comment by minjcop** [comment]
import sys
input = sys.stdin.readline
후 input() 그대로 사용해도 된다.

**Comment by micopes** [comment]
sys.stdin.readline()은 input()과 달리 '\n'도 받아서 읽는다.
이로 인해 
https://www.acmicpc.net/board/view/61754#comment-104767
와 같은 문제가 발생할 수 있다.
따라서
```
import sys
input = sys.stdin.readline
x = input().strip()
``` 
.strip()을 활용해서 공백을 제거해서 입력을 받아야 한다.
